# ArachOS Calamares Partition Module Configuration
efiSystemPartition:     "/boot/efi"
userSwapChoices:        [none, small, suspend, file]
drawNestedPartitions:   true
alwaysShowPartitionLabels: true
initialPartitioningChoice: erase
initialPartitioningName: "ArachOS"
defaultFileSystemType:  "ext4"

# Offer EVERY available filesystem to the user
availableFileSystemTypes:  ["ext4", "xfs", "btrfs", "f2fs", "jfs", "reiser", "ntfs", "exfat"]
