# ArachOS installed-system pacman configuration
[options]
HoldPkg     = pacman glibc
Architecture = x86_64
CheckSpace
SigLevel    = Required DatabaseRequired
LocalFileSigLevel = Optional

[arachos]
SigLevel = Required DatabaseRequired
Server = https://sisyphusaeolides.github.io/ArachOS/$arch

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist
