SHELL := /bin/bash

PROJECT_ROOT ?= $(abspath ..)
BUILD_DIR ?= $(CURDIR)/build
RPM_REPO ?= $(BUILD_DIR)/repo
ARACHOS_VERSION ?= 1.0
ARACHOS_RELEASE ?= 1
ARACHOS_RELEASEVER ?= 1
ARACHOS_ARCH ?= x86_64
ARACHOS_BOOTSTRAP_RELEASE ?= 45
ARACHOS_CORE_URL ?= https://dl.fedoraproject.org/pub/fedora/linux/development/45/Everything/x86_64/os/
ARACHOS_UPDATES_URL ?= https://dl.fedoraproject.org/pub/fedora/linux/updates/45/Everything/x86_64/
ARACHOS_BOOTSTRAP_ISO ?= /home/Sisyphus/Downloads/Fedora-Everything-netinst-x86_64-45-20260831.n.0.iso
ARACHOS_BOOTSTRAP_ISO_SHA256 ?= 523f17169f6012c8a9f04b1b1ceb330428a8fb1cf72e076de71dd396ffd9c40d
ARACHOS_SYSTEMD_EVR ?=
ARACHOS_REPOSITORY_URL ?=
ARACHOS_RPM_DIST ?= .arachos
ARACHOS_GPG_HOME ?=
ARACHOS_GPG_KEY_ID ?=
RPMBUILD_DBPATH ?=
RPMBUILD_TMPDIR ?=
KOJI_PROFILE ?= arachos
KOJI_TARGET ?= arachos-1.0-build
KOJI_ARCHES ?= x86_64
KOJI_CONFIG ?=
KOJI_BUILD_RPMS ?= 1
KOJI_EXPORT_REPO ?=
KOJI_TOPURL ?=
KOJI_EXPORT_ARCH ?= x86_64
CHAOS_KERNEL_PACKAGE ?= kernel-clk6.18
CHAOS_KERNEL_SRPM ?=
KERNEL_PACKAGE ?= arach-kernel
KERNEL_MODULE_PACKAGES ?=
ARACH_KERNEL_INSTALL_MANIFEST ?= $(BUILD_DIR)/kernel-bundle/install-manifest.txt
ARACHOS_HERMES_INSTALL_MANIFEST ?= $(BUILD_DIR)/hermes-qualification/release-manifest.txt
RUSTD_SOURCE_ROOT ?= $(PROJECT_ROOT)/rustd
RESOLVED_SOURCE_ROOT ?= $(PROJECT_ROOT)/rustd-resolved
ARACH_KERNEL_SOURCE_ROOT ?= $(PROJECT_ROOT)/Arach-Kernel
IWCHAOS_SOURCE_ROOT ?= $(PROJECT_ROOT)/iwchaos
TUNED_SOURCE_ROOT ?= $(PROJECT_ROOT)/tuned-rs
LIBINPUT_SOURCE_ROOT ?= $(PROJECT_ROOT)/libinput-rs
BLERUST_SOURCE_ROOT ?= $(PROJECT_ROOT)/blerust
CCZE_SOURCE_ROOT ?= $(PROJECT_ROOT)/ccze-rs
HERMES_SOURCE_ROOT ?= $(PROJECT_ROOT)/Hermes
ARACH_KERNEL_BUILD_ROOT ?= $(BUILD_DIR)/arach-kernel
ARACH_KERNEL_BUNDLE_ROOT ?= $(BUILD_DIR)/kernel-bundle
ARACH_RUSTD_STATIC_BUILD_ROOT ?= $(BUILD_DIR)/rustd-static
ARACH_KERNEL_IMAGE ?=
ARACH_RUSTD_IMAGE ?=
ARACH_BOOTSTRAP_IMAGE ?=
ARACH_RESOLVED_IMAGE ?=
ARACH_BOOTSTRAP_ABI ?= linux

.PHONY: verify-sources check-chaos qualify-hermes build-rpms build-arach-kernel-bundle \
	validate-rpms build-installer build-live build-live-existing build-live-container \
	koji-build validate clean

verify-sources:
	RUSTD_SOURCE_ROOT="$(RUSTD_SOURCE_ROOT)" \
	RESOLVED_SOURCE_ROOT="$(RESOLVED_SOURCE_ROOT)" \
	ARACH_KERNEL_SOURCE_ROOT="$(ARACH_KERNEL_SOURCE_ROOT)" \
	IWCHAOS_SOURCE_ROOT="$(IWCHAOS_SOURCE_ROOT)" \
	TUNED_SOURCE_ROOT="$(TUNED_SOURCE_ROOT)" \
	LIBINPUT_SOURCE_ROOT="$(LIBINPUT_SOURCE_ROOT)" \
	BLERUST_SOURCE_ROOT="$(BLERUST_SOURCE_ROOT)" \
	CCZE_SOURCE_ROOT="$(CCZE_SOURCE_ROOT)" \
	HERMES_SOURCE_ROOT="$(HERMES_SOURCE_ROOT)" \
	bash scripts/verify-sources.sh

build-rpms: verify-sources
	RUSTD_SOURCE_ROOT="$(RUSTD_SOURCE_ROOT)" \
	RESOLVED_SOURCE_ROOT="$(RESOLVED_SOURCE_ROOT)" \
	ARACH_KERNEL_SOURCE_ROOT="$(ARACH_KERNEL_SOURCE_ROOT)" \
	IWCHAOS_SOURCE_ROOT="$(IWCHAOS_SOURCE_ROOT)" \
	TUNED_SOURCE_ROOT="$(TUNED_SOURCE_ROOT)" \
	LIBINPUT_SOURCE_ROOT="$(LIBINPUT_SOURCE_ROOT)" \
	BLERUST_SOURCE_ROOT="$(BLERUST_SOURCE_ROOT)" \
	CCZE_SOURCE_ROOT="$(CCZE_SOURCE_ROOT)" \
	HERMES_SOURCE_ROOT="$(HERMES_SOURCE_ROOT)" \
	ARACHOS_VERSION="$(ARACHOS_VERSION)" \
	ARACHOS_RELEASE="$(ARACHOS_RELEASE)" \
	ARACHOS_RELEASEVER="$(ARACHOS_RELEASEVER)" \
	ARACHOS_BOOTSTRAP_RELEASE="$(ARACHOS_BOOTSTRAP_RELEASE)" \
	ARACHOS_CORE_URL="$(ARACHOS_CORE_URL)" \
	ARACHOS_UPDATES_URL="$(ARACHOS_UPDATES_URL)" \
	ARACHOS_BOOTSTRAP_ISO="$(ARACHOS_BOOTSTRAP_ISO)" \
	ARACHOS_BOOTSTRAP_ISO_SHA256="$(ARACHOS_BOOTSTRAP_ISO_SHA256)" \
	ARACHOS_SYSTEMD_EVR="$(ARACHOS_SYSTEMD_EVR)" \
	ARACHOS_RPM_DIST="$(ARACHOS_RPM_DIST)" \
	ARACHOS_GPG_HOME="$(ARACHOS_GPG_HOME)" \
	ARACHOS_GPG_KEY_ID="$(ARACHOS_GPG_KEY_ID)" \
	RPMBUILD_DBPATH="$(RPMBUILD_DBPATH)" \
	RPMBUILD_TMPDIR="$(RPMBUILD_TMPDIR)" \
	RPM_OUTPUT="$(BUILD_DIR)/repo" \
	bash scripts/build-rpms.sh

check-chaos: verify-sources
	IWCHAOS_SOURCE_ROOT="$(IWCHAOS_SOURCE_ROOT)" bash scripts/check-chaos.sh

qualify-hermes: verify-sources
	HERMES_QUALIFICATION_DIR="$(BUILD_DIR)/hermes-qualification" \
	HERMES_RELEASE_MANIFEST="$(ARACHOS_HERMES_INSTALL_MANIFEST)" \
	bash "$(HERMES_SOURCE_ROOT)/scripts/qualify-release.sh"

build-arach-kernel-bundle: build-rpms
	ARACH_KERNEL_SOURCE_ROOT="$(ARACH_KERNEL_SOURCE_ROOT)" \
	ARACH_KERNEL_BUILD_ROOT="$(ARACH_KERNEL_BUILD_ROOT)" \
	ARACH_KERNEL_BUNDLE_ROOT="$(ARACH_KERNEL_BUNDLE_ROOT)" \
	ARACH_KERNEL_IMAGE="$(ARACH_KERNEL_IMAGE)" \
	ARACH_RUSTD_IMAGE="$(ARACH_RUSTD_IMAGE)" \
	ARACH_RUSTD_STATIC_BUILD_ROOT="$(ARACH_RUSTD_STATIC_BUILD_ROOT)" \
	ARACH_BOOTSTRAP_IMAGE="$(ARACH_BOOTSTRAP_IMAGE)" \
	ARACH_RESOLVED_IMAGE="$(ARACH_RESOLVED_IMAGE)" \
	ARACH_BOOTSTRAP_ABI="$(ARACH_BOOTSTRAP_ABI)" \
	ARACHOS_VERSION="$(ARACHOS_VERSION)" \
	ARACHOS_RELEASE="$(ARACHOS_RELEASE)" \
	ARACHOS_RPM_DIST="$(ARACHOS_RPM_DIST)" \
	RUSTD_SOURCE_ROOT="$(RUSTD_SOURCE_ROOT)" \
	RESOLVED_SOURCE_ROOT="$(RESOLVED_SOURCE_ROOT)" \
	IWCHAOS_SOURCE_ROOT="$(IWCHAOS_SOURCE_ROOT)" \
	TUNED_SOURCE_ROOT="$(TUNED_SOURCE_ROOT)" \
	LIBINPUT_SOURCE_ROOT="$(LIBINPUT_SOURCE_ROOT)" \
	BLERUST_SOURCE_ROOT="$(BLERUST_SOURCE_ROOT)" \
	CCZE_SOURCE_ROOT="$(CCZE_SOURCE_ROOT)" \
	HERMES_SOURCE_ROOT="$(HERMES_SOURCE_ROOT)" \
	ARACHOS_GPG_HOME="$(ARACHOS_GPG_HOME)" \
	ARACHOS_GPG_KEY_ID="$(ARACHOS_GPG_KEY_ID)" \
	RPM_REPO="$(RPM_REPO)" \
	bash scripts/build-arach-kernel-bundle.sh

validate-rpms:
	RPM_REPO="$(RPM_REPO)" bash scripts/validate-rpms.sh

build-installer: qualify-hermes build-rpms build-arach-kernel-bundle validate-rpms
	RPM_REPO="$(RPM_REPO)" ISO_OUTPUT="$(BUILD_DIR)/iso" \
	ARACHOS_VERSION="$(ARACHOS_VERSION)" ARACHOS_RELEASE="$(ARACHOS_RELEASE)" \
	ARACHOS_RELEASEVER="$(ARACHOS_RELEASEVER)" \
	ARACHOS_ARCH="$(ARACHOS_ARCH)" \
	ARACHOS_BOOTSTRAP_RELEASE="$(ARACHOS_BOOTSTRAP_RELEASE)" \
	ARACHOS_CORE_URL="$(ARACHOS_CORE_URL)" \
	ARACHOS_UPDATES_URL="$(ARACHOS_UPDATES_URL)" \
	ARACHOS_BOOTSTRAP_ISO="$(ARACHOS_BOOTSTRAP_ISO)" \
	ARACHOS_BOOTSTRAP_ISO_SHA256="$(ARACHOS_BOOTSTRAP_ISO_SHA256)" \
	ARACHOS_REPOSITORY_URL="$(ARACHOS_REPOSITORY_URL)" \
	ARACHOS_GPG_HOME="$(ARACHOS_GPG_HOME)" \
	ARACHOS_GPG_KEY_ID="$(ARACHOS_GPG_KEY_ID)" \
	KERNEL_PACKAGE="$(KERNEL_PACKAGE)" \
	KERNEL_MODULE_PACKAGES="$(KERNEL_MODULE_PACKAGES)" \
	ARACH_KERNEL_INSTALL_MANIFEST="$(ARACH_KERNEL_INSTALL_MANIFEST)" \
	ARACHOS_HERMES_INSTALL_MANIFEST="$(ARACHOS_HERMES_INSTALL_MANIFEST)" \
	RUSTD_SOURCE_ROOT="$(RUSTD_SOURCE_ROOT)" \
		bash scripts/build-live.sh

build-live: build-installer

build-live-existing: qualify-hermes validate-rpms
	RPM_REPO="$(RPM_REPO)" ISO_OUTPUT="$(BUILD_DIR)/iso" \
	ARACHOS_VERSION="$(ARACHOS_VERSION)" ARACHOS_RELEASE="$(ARACHOS_RELEASE)" \
	ARACHOS_RELEASEVER="$(ARACHOS_RELEASEVER)" \
	ARACHOS_ARCH="$(ARACHOS_ARCH)" \
	ARACHOS_BOOTSTRAP_RELEASE="$(ARACHOS_BOOTSTRAP_RELEASE)" \
	ARACHOS_CORE_URL="$(ARACHOS_CORE_URL)" \
	ARACHOS_UPDATES_URL="$(ARACHOS_UPDATES_URL)" \
	ARACHOS_BOOTSTRAP_ISO="$(ARACHOS_BOOTSTRAP_ISO)" \
	ARACHOS_BOOTSTRAP_ISO_SHA256="$(ARACHOS_BOOTSTRAP_ISO_SHA256)" \
	ARACHOS_REPOSITORY_URL="$(ARACHOS_REPOSITORY_URL)" \
	KERNEL_PACKAGE="$(KERNEL_PACKAGE)" \
	KERNEL_MODULE_PACKAGES="$(KERNEL_MODULE_PACKAGES)" \
	ARACH_KERNEL_INSTALL_MANIFEST="$(ARACH_KERNEL_INSTALL_MANIFEST)" \
	ARACHOS_HERMES_INSTALL_MANIFEST="$(ARACHOS_HERMES_INSTALL_MANIFEST)" \
	bash scripts/build-live.sh

build-live-container: qualify-hermes validate-rpms
	RPM_REPO="$(RPM_REPO)" \
	ARACHOS_VERSION="$(ARACHOS_VERSION)" ARACHOS_RELEASE="$(ARACHOS_RELEASE)" \
	ARACHOS_RELEASEVER="$(ARACHOS_RELEASEVER)" \
	ARACHOS_ARCH="$(ARACHOS_ARCH)" \
	ARACHOS_BOOTSTRAP_RELEASE="$(ARACHOS_BOOTSTRAP_RELEASE)" \
	ARACHOS_CORE_URL="$(ARACHOS_CORE_URL)" \
	ARACHOS_UPDATES_URL="$(ARACHOS_UPDATES_URL)" \
	ARACHOS_BOOTSTRAP_ISO="$(ARACHOS_BOOTSTRAP_ISO)" \
	ARACHOS_BOOTSTRAP_ISO_SHA256="$(ARACHOS_BOOTSTRAP_ISO_SHA256)" \
	ARACHOS_REPOSITORY_URL="$(ARACHOS_REPOSITORY_URL)" \
	KERNEL_PACKAGE="$(KERNEL_PACKAGE)" \
	KERNEL_MODULE_PACKAGES="$(KERNEL_MODULE_PACKAGES)" \
	ARACH_KERNEL_INSTALL_MANIFEST="$(ARACH_KERNEL_INSTALL_MANIFEST)" \
	ARACHOS_HERMES_INSTALL_MANIFEST="$(ARACHOS_HERMES_INSTALL_MANIFEST)" \
	bash scripts/build-live-container.sh

koji-build:
	ARACHOS_VERSION="$(ARACHOS_VERSION)" \
		ARACHOS_RELEASE="$(ARACHOS_RELEASE)" \
		ARACHOS_BOOTSTRAP_RELEASE="$(ARACHOS_BOOTSTRAP_RELEASE)" \
		KOJI_PROFILE="$(KOJI_PROFILE)" KOJI_TARGET="$(KOJI_TARGET)" \
		KOJI_ARCHES="$(KOJI_ARCHES)" \
		CHAOS_KERNEL_PACKAGE="$(CHAOS_KERNEL_PACKAGE)" \
		CHAOS_KERNEL_SRPM="$(CHAOS_KERNEL_SRPM)" \
		KOJI_EXPORT_REPO="$(KOJI_EXPORT_REPO)" KOJI_TOPURL="$(KOJI_TOPURL)" \
		KOJI_EXPORT_ARCH="$(KOJI_EXPORT_ARCH)" \
		RPM_REPO="$(BUILD_DIR)/repo" \
		KOJI_CONFIG="$(KOJI_CONFIG)" KOJI_BUILD_RPMS="$(KOJI_BUILD_RPMS)" \
		bash scripts/build-koji.sh

validate: verify-sources check-chaos validate-rpms

clean:
	rm -rf "$(BUILD_DIR)"
