# ArachOS build system — archiso / pacman

ARACHOS_VERSION        ?= 1.0
ARACHOS_RELEASE        ?= 1
ARACHOS_ARCH           ?= x86_64
ARACHOS_REPOSITORY_URL ?=
ARACHOS_KEEP_BUILD_WORK ?= 0
ARACHOS_GPG_HOME       ?=
ARACHOS_GPG_KEY_ID     ?=
ARACHOS_KERNEL_PACKAGE ?= arach-kernel

BUILD_DIR              ?= build
PKG_REPO               ?= $(PWD)/$(BUILD_DIR)/packages
ISO_OUTPUT             ?= $(BUILD_DIR)/iso

RUSTD_SOURCE_ROOT        ?= ../rustd
RESOLVED_SOURCE_ROOT     ?= ../rustd-resolved
ARACH_KERNEL_SOURCE_ROOT ?= ../arach-kernel
IWCHAOS_SOURCE_ROOT      ?= ../iwchaos
TUNED_SOURCE_ROOT        ?= ../tuned-rs
LIBINPUT_SOURCE_ROOT     ?= ../libinput-rs
BLERUST_SOURCE_ROOT      ?= ../blerust
CCZE_SOURCE_ROOT         ?= ../ccze-rs
HERMES_SOURCE_ROOT       ?= ../Hermes

ARACH_KERNEL_BUNDLE_ROOT         ?= $(BUILD_DIR)/kernel-bundle
ARACH_RUSTD_STATIC_BUILD_ROOT    ?= $(BUILD_DIR)/rustd-static
ARACH_KERNEL_INSTALL_MANIFEST    ?= $(BUILD_DIR)/kernel-bundle/install-manifest.txt
ARACHOS_HERMES_INSTALL_MANIFEST  ?= $(BUILD_DIR)/hermes-qualification/release-manifest.txt
ARACHOS_INSTALLER_KERNEL         ?= $(BUILD_DIR)/kernel-bundle/arach
ARACHOS_INSTALLER_INITRD         ?= $(BUILD_DIR)/kernel-bundle/bootstrap
ARACHOS_LIVE_RUNTIME_MANIFEST    ?= $(BUILD_DIR)/kernel-bundle/live-manifest.txt

ARACH_KERNEL_IMAGE  ?=
ARACH_RUSTD_IMAGE   ?=
ARACH_BOOTSTRAP_IMAGE ?=
ARACH_RESOLVED_IMAGE  ?=
ARACH_BOOTSTRAP_ABI   ?= linux

.PHONY: verify-sources check-chaos qualify-hermes build-packages \
	build-arach-kernel-bundle validate-packages sign-packages \
	build-iso test-kernel-qemu validate clean

verify-sources:
	RUSTD_SOURCE_ROOT="$(RUSTD_SOURCE_ROOT)" \
	RESOLVED_SOURCE_ROOT="$(RESOLVED_SOURCE_ROOT)" \
	ARACH_KERNEL_SOURCE_ROOT="$(ARACH_KERNEL_SOURCE_ROOT)" \
	IWCHAOS_SOURCE_ROOT="$(IWCHAOS_SOURCE_ROOT)" \
	TUNED_SOURCE_ROOT="$(TUNED_SOURCE_ROOT)" \
	LIBINPUT_SOURCE_ROOT="$(LIBINPUT_SOURCE_ROOT)" \
	BLERUST_SOURCE_ROOT="$(BLERUST_SOURCE_ROOT)" \
	CCZE_SOURCE_ROOT="$(CCZE_SOURCE_ROOT)" \
	HERMES_SOURCE_ROOT="$(HERMES_SOURCE_ROOT)" \
	bash scripts/verify-sources.sh

check-chaos: verify-sources
	IWCHAOS_SOURCE_ROOT="$(IWCHAOS_SOURCE_ROOT)" bash scripts/check-chaos.sh

qualify-hermes: verify-sources
	HERMES_QUALIFICATION_DIR="$(BUILD_DIR)/hermes-qualification" \
	HERMES_RELEASE_MANIFEST="$(ARACHOS_HERMES_INSTALL_MANIFEST)" \
	bash "$(HERMES_SOURCE_ROOT)/scripts/qualify-release.sh"

build-packages: verify-sources
	RUSTD_SOURCE_ROOT="$(RUSTD_SOURCE_ROOT)" \
	RESOLVED_SOURCE_ROOT="$(RESOLVED_SOURCE_ROOT)" \
	ARACH_KERNEL_SOURCE_ROOT="$(ARACH_KERNEL_SOURCE_ROOT)" \
	IWCHAOS_SOURCE_ROOT="$(IWCHAOS_SOURCE_ROOT)" \
	TUNED_SOURCE_ROOT="$(TUNED_SOURCE_ROOT)" \
	LIBINPUT_SOURCE_ROOT="$(LIBINPUT_SOURCE_ROOT)" \
	BLERUST_SOURCE_ROOT="$(BLERUST_SOURCE_ROOT)" \
	CCZE_SOURCE_ROOT="$(CCZE_SOURCE_ROOT)" \
	HERMES_SOURCE_ROOT="$(HERMES_SOURCE_ROOT)" \
	ARACHOS_VERSION="$(ARACHOS_VERSION)" \
	ARACHOS_RELEASE="$(ARACHOS_RELEASE)" \
	ARACHOS_KEEP_BUILD_WORK="$(ARACHOS_KEEP_BUILD_WORK)" \
	ARACHOS_GPG_HOME="$(ARACHOS_GPG_HOME)" \
	ARACHOS_GPG_KEY_ID="$(ARACHOS_GPG_KEY_ID)" \
	PKG_OUTPUT="$(PKG_REPO)" \
	bash scripts/build-packages.sh

build-arach-kernel-bundle: build-packages
	ARACH_KERNEL_SOURCE_ROOT="$(ARACH_KERNEL_SOURCE_ROOT)" \
	ARACH_KERNEL_BUNDLE_ROOT="$(ARACH_KERNEL_BUNDLE_ROOT)" \
	ARACH_KERNEL_IMAGE="$(ARACH_KERNEL_IMAGE)" \
	ARACH_RUSTD_IMAGE="$(ARACH_RUSTD_IMAGE)" \
	ARACH_RUSTD_STATIC_BUILD_ROOT="$(ARACH_RUSTD_STATIC_BUILD_ROOT)" \
	ARACH_BOOTSTRAP_IMAGE="$(ARACH_BOOTSTRAP_IMAGE)" \
	ARACH_RESOLVED_IMAGE="$(ARACH_RESOLVED_IMAGE)" \
	ARACH_BOOTSTRAP_ABI="$(ARACH_BOOTSTRAP_ABI)" \
	ARACHOS_VERSION="$(ARACHOS_VERSION)" \
	ARACHOS_RELEASE="$(ARACHOS_RELEASE)" \
	ARACHOS_KEEP_BUILD_WORK="$(ARACHOS_KEEP_BUILD_WORK)" \
	RUSTD_SOURCE_ROOT="$(RUSTD_SOURCE_ROOT)" \
	RESOLVED_SOURCE_ROOT="$(RESOLVED_SOURCE_ROOT)" \
	IWCHAOS_SOURCE_ROOT="$(IWCHAOS_SOURCE_ROOT)" \
	TUNED_SOURCE_ROOT="$(TUNED_SOURCE_ROOT)" \
	LIBINPUT_SOURCE_ROOT="$(LIBINPUT_SOURCE_ROOT)" \
	BLERUST_SOURCE_ROOT="$(BLERUST_SOURCE_ROOT)" \
	CCZE_SOURCE_ROOT="$(CCZE_SOURCE_ROOT)" \
	HERMES_SOURCE_ROOT="$(HERMES_SOURCE_ROOT)" \
	ARACHOS_GPG_HOME="$(ARACHOS_GPG_HOME)" \
	ARACHOS_GPG_KEY_ID="$(ARACHOS_GPG_KEY_ID)" \
	PKG_REPO="$(PKG_REPO)" \
	bash scripts/build-arach-kernel-bundle.sh

validate-packages:
	PKG_REPO="$(PKG_REPO)" bash scripts/validate-packages.sh

sign-packages:
	ARACHOS_GPG_HOME="$(ARACHOS_GPG_HOME)" \
	ARACHOS_GPG_KEY_ID="$(ARACHOS_GPG_KEY_ID)" \
	bash scripts/sign-pkg-repo.sh "$(PKG_REPO)"

build-iso:
	PKG_REPO="$(PKG_REPO)" \
	ISO_OUTPUT="$(ISO_OUTPUT)" \
	ARACHOS_VERSION="$(ARACHOS_VERSION)" \
	ARACHOS_RELEASE="$(ARACHOS_RELEASE)" \
	ARACHOS_ARCH="$(ARACHOS_ARCH)" \
	ARACHOS_REPOSITORY_URL="$(ARACHOS_REPOSITORY_URL)" \
	ARACHOS_INSTALLER_KERNEL="$(ARACHOS_INSTALLER_KERNEL)" \
	ARACHOS_INSTALLER_INITRD="$(ARACHOS_INSTALLER_INITRD)" \
	ARACHOS_LIVE_RUNTIME_MANIFEST="$(ARACHOS_LIVE_RUNTIME_MANIFEST)" \
	LIVE_MEDIA_KEEP_WORK="$(LIVE_MEDIA_KEEP_WORK)" \
	ARACHOS_GPG_HOME="$(ARACHOS_GPG_HOME)" \
	ARACHOS_GPG_KEY_ID="$(ARACHOS_GPG_KEY_ID)" \
	ARACH_KERNEL_INSTALL_MANIFEST="$(ARACH_KERNEL_INSTALL_MANIFEST)" \
	ARACHOS_HERMES_INSTALL_MANIFEST="$(ARACHOS_HERMES_INSTALL_MANIFEST)" \
	ARACHOS_KERNEL_PACKAGE="$(ARACHOS_KERNEL_PACKAGE)" \
	bash scripts/build-iso.sh

test-kernel-qemu:
	bash scripts/test-kernel-qemu.sh

validate: verify-sources check-chaos validate-packages

clean:
	rm -rf "$(BUILD_DIR)"
