# ArachOS Calamares Settings
modules-search: [ local ]

instances:
- id:       arachos
  module:   netinstall
  config:   netinstall.conf
- id:       arachos-kernel
  module:   shellprocess
  config:   shellprocess-arach-kernel.conf
- id:       arachos-rustd
  module:   shellprocess
  config:   shellprocess-rustd.conf

sequence:
- show:
  - welcome
  - locale
  - keyboard
  - partition
  - users
  - netinstall@arachos
  - summary
- exec:
  - partition
  - mount
  - unpackfs
  - machineid
  - fstab
  - locale
  - keyboard
  - localecfg
  - users
  - displaymanager
  - networkcfg
  - hwclock
  - shellprocess@arachos-rustd
  - arachos-packages
  - grubcfg
  - bootloader
  - shellprocess@arachos-kernel
  - umount
- show:
  - finished

branding: arachos
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: false
hide-back-and-next-during-exec: false
quit-at-end: false
