# ArachOS archiso pacman configuration
[options]
HoldPkg     = pacman glibc
Architecture = x86_64
CheckSpace
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[sisyphus]
SigLevel = Required DatabaseOptional
Server = https://sisyphusaeolides.github.io/Sisyphus-Repo/$arch

[arachos]
SigLevel = Optional TrustAll
Server = file:///home/Sisyphus/Projects/ArachOS/build/packages

[cachyos]
Include = /etc/pacman.d/cachyos-mirrorlist

[cachyos-core-v3]
Include = /etc/pacman.d/cachyos-v3-mirrorlist

[cachyos-extra-v3]
Include = /etc/pacman.d/cachyos-v3-mirrorlist
