# ArachOS archiso pacman configuration
[options]
HoldPkg     = pacman glibc
Architecture = x86_64
CheckSpace
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

[arachos]
SigLevel = Optional TrustAll
Server = file:///home/Sisyphus/Projects/ArachOS/build/packages

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist
