# ArachOS archiso pacman configuration
[options]
HoldPkg     = pacman glibc
Architecture = x86_64
CheckSpace
SigLevel    = Required DatabaseRequired
LocalFileSigLevel = Optional

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

#[cachyos]
#Include = /etc/pacman.d/cachyos-mirrorlist

[cachyos-core-v3]
#Include = /etc/pacman.d/cachyos-mirrorlist

[cachyos-extra-v3]
#Include = /etc/pacman.d/cachyos-mirrorlist

[sisyphus]
SigLevel = Required DatabaseRequired
Server = https://sisyphusaeolides.github.io/Sisyphus-Repo/$arch

[arachos]
SigLevel = Required DatabaseRequired
Server = ${ARACHOS_REPOSITORY_URL:-https://sisyphusaeolides.github.io/ArachOS/$arch}

[arachos-local]
SigLevel = Optional TrustAll
Server = file://build/packages
