i18n:
     name: "Installing Arach Kernel boot contract"
dontChroot: false
timeout: 60
script:
    - "-/usr/sbin/arach-kernel-install --root=/ --install --kernel=/boot/arach --rustd=/boot/rustd --resolved=/boot/rustd-resolved"
